profile_app/urls.py
from django.urls import path
from . import views

app_name = "profile"
urlpatterns = [
    path("create/", views.Create.as_view(), name="create"),
    path("search/", views.profile_all, name='search'),
    path("update/", views.Update.as_view(), name='update'),
    path("unfollow/", views.unfollow, name='unfollow'),
    path("follow/", views.follow, name='follow'),
    path("<id>/", views.Detail.as_view(), name="detail"),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core_app.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet_app/urls.py
from django.urls import path
from . import views


app_name = "tweet"
urlpatterns = [
    path("create/", views.Create.as_view(), name='create'),
    path('likes/<pk>/', views.like, name='like'),
    path('<pk>/', views.Detail.as_view(), name='detail'),
]

core_app/models.py
from django.db.models.fields import related, related_descriptors
from django.utils import timezone
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
import os

# Create your models here.

def media_directory_path(instance, filename):
    return os.path.join("post", str(instance.tweet.id), filename)


User = get_user_model()

class Relation(models.Model):
    follower = models.ForeignKey(User, models.CASCADE, related_name='follower_set')
    following = models.ForeignKey(User, models.CASCADE, related_name='following_set')

class Profile(models.Model):
    user = models.OneToOneField(User, models.CASCADE)
    name = models.CharField(max_length=20)
    photo = models.ImageField(upload_to="photo", null=True, blank=True)
    cover_photo = models.ImageField(upload_to="photo", null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def unfollow(self, user):
        relation = Relation.objects.filter(following=user, follower=self.user).first()
        if relation:
            relation.delete()

    def follow(self, user):
        relation = Relation.objects.create(following=user, follower=self.user)
        relation.save()
    
    @property
    def following(self):
        return User.objects.filter(
            id__in=[relation.following.id for relation in Relation.objects.filter(follower=self.user)]
        )

    @property
    def followers(self):
        return User.objects.filter(
            id__in=[relation.follower.id for relation in Relation.objects.filter(following=self.user)]
        )


class Tweet(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    text = models.TextField(null=True, blank=True)
    likes = models.ManyToManyField(User, "posts_liked", blank=True)
    shares = models.ManyToManyField(User, "posts_shared", blank=True)
    mentions = models.ManyToManyField(User, 'tweet_mentions', blank=True)
    reply_mode = models.CharField(
        max_length=10,
        choices=(
            ('everyone', 'Everyone can reply'),
            ('following', 'People you follow'),
            ('mentioned', 'Only people you mention')
        ),
        default='everyone'
    )
    reply_to = models.ForeignKey("self", models.CASCADE, blank=True, null=True, related_name='replies')
    retweet = models.ForeignKey("self", models.CASCADE, blank=True, null=True, related_name='retweets')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-created_at']

    def liked_by(self, user):
        return self.likes.filter(id=user.id).first() != None

    def time_passed(self):
        delta = self.created_at - timezone.now()

class Comment(models.Model):
    tweet = models.ForeignKey(Tweet, models.CASCADE)
    user = models.ForeignKey(User, models.CASCADE)
    text = models.TextField()

class Media(models.Model):
    tweet = models.ForeignKey(Tweet, models.CASCADE)
    file = models.FileField(upload_to=media_directory_path)
    content_type = models.CharField(max_length=20)

tweet_app/models.py
from django.db import models

# Create your models here.

tweet_app/forms.py
from django import forms
from core_app import models

class TweetForm(forms.ModelForm):
    class Meta:
        model = models.Tweet
        fields = ['text', 'reply_mode', 'reply_to']

tweet_app/views.py
from django.shortcuts import Http404, get_object_or_404, redirect, render
from django.urls.base import reverse
from django.views import View
from django.contrib.auth import decorators
from django.http import request, response
from . import forms
from core_app import models, mixins
import json
import re

# Create your views here.

class Create(mixins.ProfileRequired, View):
    template_name = "tweet_app/create.html"
    def get(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        ctx['form'] = forms.TweetForm()
        ctx['profiles'] = models.Profile.objects.all()
        return render(req, self.template_name, ctx)

    def post(self, req: request.HttpRequest, *args, **kwargs):
        mentions = json.loads(req.POST.get('mentions') or "[]")
        ctx = {}
        form = forms.TweetForm(req.POST)
        print(form.data)
        image = req.FILES.get('image')
        video = req.FILES.get('video')
        ctx['form'] = form
        if image != None:
            if image.content_type not in ["image/png", "image/jpeg"]:
                ctx['error'] = "invalid content_type for image"
                print(ctx['error'])
                return render(req, self.template_name, ctx)
        if video != None:
            if video.content_type not in ["video/mp4", "video/3gp"]:
                ctx['error'] = "invalid content_type for video"
                print(ctx['error'])
                return render(req, self.template_name, ctx)
        if not form.is_valid():
            ctx['error'] = "invalid input"
            return render(req, self.template_name, ctx)
        data = form.cleaned_data #text, reply_mode, mentions, reply_to
        reply_to = data.get('reply_to')
        if reply_to and reply_to.user != req.user:
            if reply_to.reply_mode == 'mentioned':
                if reply_to.mentions.filter(id=req.user.id).first() == None:
                    return response.HttpResponse("only mentioned can reply")
            if reply_to.reply_mode == 'following':
                if reply_to.user.profile.following.filter(id=req.user.id).first() == None:
                    return response.HttpResponse("only followed can reply")

        if re.match('^\s+$', data['text']) or len(data['text']) <= 0:
            if not (image or video):
                ctx['error'] = "provide at least one of text, video or image"
                return render(req, self.template_name, ctx)
        tweet = models.Tweet.objects.create(
            user=req.user,
            **data
        )
        if image != None:
            image = models.Media.objects.create(
                tweet=tweet,
                file=image,
                content_type=image.content_type
            )
        if video != None:
            video = models.Media.objects.create(
                tweet=tweet,
                file=video,
                content_type=video.content_type
            )
        tweet.mentions.add(*mentions)
        tweet.save()
        if image: image.save()
        if video: video.save()
        return redirect(reverse('index'))

class Detail(mixins.ProfileRequired, View):
    template_name = 'tweet_app/detail.html'
    def get(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        ctx['tweet'] = get_object_or_404(
            models.Tweet,
            id=kwargs.get('pk')
        )
        return render(req, self.template_name, ctx)

@decorators.login_required
def like(req: request.HttpRequest, *args, **kwargs):
    ctx = {}
    tweet = get_object_or_404(
        models.Tweet,
        pk=kwargs.get('pk')
    )
    if tweet.likes.filter(id=req.user.id):
        tweet.likes.remove(req.user)
        ctx['action'] = 'remove'
    else:
        tweet.likes.add(req.user)
        ctx['action'] = 'add'
    ctx['success'] = True
    return response.JsonResponse(ctx)

templates/tweet_app/create.html
{% extends 'skeleton/tulang.html' %}
{% block body %}
<div class="w-full bg-gray-100">
	<div class="max-w-xl w-full m-auto bg-white h-screen relative">
		<form id="content" class="w-full px-3 py-3" method="post" enctype="multipart/form-data" action="{% url 'tweet:create' %}">
			<input name="mentions" type="hidden" value="[]">
			<nav class="flex items-center justify-between peer-placeholder-shown:bg-blue-300">
				<button onclick="location.assign('/'); event.preventDefault()"><i class="fas fa-arrow-left"></i></button>
				<button disabled type="submit" class="bg-blue-300 px-4 py-1 rounded-full text-white">Tweet</button>
			</nav>
			<div class="flex gap-3 my-5">
				<div class="w-14 h-14 rounded-full bg-red-50 flex-shrink-0"></div>
				<div class="w-full">
					<textarea name="text" class="outline-none resize-none overflow-scroll min-h-[120px] max-h-[200px] w-full placeholder:text-xl placeholder:text-gray-500" placeholder="What's happening?"></textarea>
					<!-- image -->
					<div id="image-div" class="hidden bg-blue-100">
						<img class="aspect-video object-cover">
					</div>
					<!-- image -->
					<!-- users -->
					<div id="users" class="w-full">
					</div>
					<!-- users -->
					<div>
						<div>
							<output onclick="open_select()" class="font-bold text-blue-400 text-sm" id="reply_mode_output"></output>
							<select class="hidden" name="{{ form.reply_mode.name }}">
								{% for option in form.reply_mode.field.choices %}
								<option value="{{ option.0 }}">{{ option.1 }}</option>
								{% endfor %}
							</select>
						</div>
						<hr class="my-2">
						<div class="flex gap-4">
							<label>
								<i class="fal fa-image text-blue-400 text-lg"></i>
								<input onchange="btn.disabled=false;imgDiv.querySelector('img').src=window.URL.createObjectURL(this.files[0]);imgDiv.classList.remove('hidden')" type="file" class="hidden" name="image">
							</label>
							<label>
								<i class="fal fa-video text-blue-400 text-lg"></i>
								<input onchange="btn.disabled=false" type="file" class="hidden" name="video">
							</label>
						</div>
					</div>
				</div>
			</div>
		</form>
		<!-- reply_mode options -->
		<div id="reply_mode_options" class="absolute bottom-0 left-0 w-full bg-white shadow-md border hidden flex-col rounded-[20px_20px_0_0]">
			<div class="m-3">
				<h6 class="font-bold">Who can reply?</h6>
				<small class="text-gray-500">Choose who can reply to this Tweet. Anyone mentioned can always reply.</small>
			</div>
			<div class="flex flex-col">
				{% for option in form.reply_mode.field.choices %}
				<label class="text-sm text-gray-600 flex items-center hover:bg-gray-100 p-3">
					<i class="fas fa-circle-x mr-5 text-4xl text-blue-400"></i>{{ option.1 }}
					<input class="hidden" name="option" type="radio" value="{{ forloop.counter0 }}" onchange="change_selected(reply_mode, this.value)">
				</label>
				{% endfor %}
			</div>
			<button onclick="close_select()" class="border rounded-full py-2 w-auto m-3 hover:bg-gray-100">Cancel</button>
		</div>
		<!-- reply_mode options -->
	</div>
</div>
<!-- dummy el -->
<div class="hidden">
	<div class="bg-blue-400 flex blur-sm bg-gray-100 border-t"></div>
	<div class="w-full">
		{% for profile in profiles %}
		<div class="hover:bg-gray-100 p-2 flex items-center gap-3">
			<div class="w-12 h-12 rounded-full overflow-hidden flex-shrink-0">
				{% if profile.photo %}
				<img class="w-full h-full object-cover" src="{{ profile.photo.url }}">
				{% endif %}
			</div>
			<div class="w-full">
				<h5 class="font-bold">{{ profile.user.username }}</h5>
				<span class="text-gray-500">{{ profile.name }}</span>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<!-- dummy el -->
<script>
	let imgDiv = document.getElementById('image-div')
	let text = document.querySelector("[name='text']")
	let btn = document.querySelector("[type='submit']")
	text.oninput=()=>{
			watch()
			auto_grow(text)
			if(text.value){
					btn.classList.replace('bg-blue-300', 'bg-blue-400')
					btn.disabled = false
				}else{
						btn.classList.replace('bg-blue-400', 'bg-blue-300')
						btn.disabled = true
					}
		}
	function auto_grow(e){
			e.style.height = "5px"
			e.style.height = `${e.scrollHeight}px`
		}

	let reply_mode = document.getElementsByName("{{ form.reply_mode.name }}")[0]
	let options = reply_mode.querySelectorAll('option')
	let output = document.getElementById('reply_mode_output')
	reply_mode.onchange = ()=>{
			update_select(reply_mode, output)
		}
	function update_select(select, output){
			let options = select.querySelectorAll('option')
			options.forEach(e=>{
					if(e.value == reply_mode.value){
							output.value = e.innerHTML
						}
				})
		}
	update_select(reply_mode, output)
	function open_select(){
			document.querySelector("#reply_mode_options").classList.replace("hidden", "flex")
			document.getElementById("content").classList.add("blur-sm")
		}

	function change_selected(select, val){
			close_select()
			select.selectedIndex = parseInt(val)
			update_select(select, output)
		}

	function close_select(){
			document.querySelector("#reply_mode_options").classList.replace("flex", "hidden")
			document.getElementById("content").classList.remove("blur-sm")
	}

	let name = null

	function watch(){
			let chr = text.value[text.value.length - 1]
			if (chr == "@"){
				name = ""
				}else if ((""+chr).match(/\s/)){
						document.getElementById("users").innerHTML = ""
		document.getElementById("users").classList.remove('border-t')
					}
			else if (name != null){
					name+=chr
					fetch(`{% url 'profile:search' %}?name=${name}`).then(res=>{
							res.json().then(val=>{
									document.getElementById("users").innerHTML = ""
									for(let v of val.profiles){
											console.log(add_user(v))
										}
								})
						})
				}
		}
	function add_user(profile){
			let template = `
				<div onclick='add_mention(${profile.id}, "${profile.user.username}")' class="hover:bg-gray-100 p-2 flex items-center gap-3">
			<div class="w-12 h-12 rounded-full overflow-hidden flex-shrink-0">
				${ profile.photo ? `<img class="w-full h-full object-cover" src="${ profile.photo }">` : "" } 
			</div>
			<div class="w-full">
				<h5 class="font-bold">${ profile.name }</h5>
				<span class="text-gray-500">@${ profile.user.username }</span>
			</div>
		</div>
			`
		document.getElementById("users").innerHTML += template
		document.getElementById("users").classList.add('border-t')
	}

	function add_mention(id, nameprofile){
			let mentions = document.querySelector("[name='mentions']")
			let v = JSON.parse(mentions.value)
			if (v.indexOf(id) < 0){
					v.push(id)
				let r = JSON.stringify(v)
					mentions.value = r
				}
			text.value = text.value.replace(/@[a-zA-Z0-9]*$/, `@${nameprofile}`)
		document.getElementById("users").innerHTML = ''
		document.getElementById("users").classList.remove('border-t')
		text.focus()
	}
</script>
{% endblock %}

templates/tweet_app/detail.html
{% extends 'skeleton/tulang.html' %}
{% load humanize %}
{% load core %}
{% block body %}
<div class="bg-gray-300">
	<div class="max-w-xl m-auto bg-white min-h-screen">
		<nav class="sticky w-full top-0 left-0 p-3 backdrop-blur-md flex gap-10">
			<button onclick="history.back()"><i class="fas fa-arrow-left"></i></button>
			<div>
				<h2 class="font-bold text-xl">Tweet</h2>
			</div>
		</nav>
		<div class="px-3">
			<div class="py-3 flex gap-3 items-center">
				<div class="w-16 h-16 rounded-full overflow-hidden bg-gray-300 flex items-center justify-center ring-[1px] flex-shrink-0">
					{% if tweet.user.profile.photo %}
					<img class="w-full h-full object-cover" src="{{ tweet.user.profile.photo.url }}">
					{% else %}
					<i class="fas fa-user text-white text-3xl"></i>
					{% endif %}
				</div>
				<div class="flex items-center justify-between w-full">
					<div>
						<a href="{% url 'profile:detail' tweet.user.profile.id %}">
							<h3 class="font-bold text-xl">{{ tweet.user.profile.name }}</h3>
							<h6 class="text-gray-500">@{{ tweet.user.username }}</h6>
						</a>
					</div>
					<button><i class="fal fa-ellipsis text-xl"></i></button>
				</div>
			</div>
			{% if tweet.reply_to %}
			<div class="text-xs">
				<span class="text-gray-500">Replying to </span><a href="{% url 'tweet:detail' tweet.reply_to.id %}" class="text-blue-400">@{{ tweet.reply_to.user }}</a>
			</div>
			{% endif %}
			<p class="text-xl">
			{{ tweet.text }}
			</p>
			{% if tweet.media_set.count %}
			<div class="py-3">
				{% for media in tweet.media_set.all %}
					{% if media.content_type == "image/jpeg" or media.content_type == "image/png" %}
					<div class="w-full rounded-xl max-h-80 overflow-hidden ring-[1px] ring-gray-300 mt-2">
						<img class="w-full h-full object-cover" src="{{ media.file.url }}">
					</div>
					{% elif media.content_type == "video/mp4" or media.content_type == "video/3gp" %}
					<div class="w-full rounded-xl max-h-80 overflow-hidden ring-[1px] ring-gray-300 mt-2">
						<video controls class="w-full h-full object-cover" src="{{ media.file.url }}"></video>
					</div>
					{% endif %}			
				{% endfor %}
			</div>
			{% endif %}
			<div class="divide-y">
				<div class="p-3 flex items-center gap-1 text-gray-500">
					<span>
						{{ tweet.created_at|date:"g:i A" }}
					</span>
					<div class="border rounded-full border-gray-400"></div>
					<span>
						{{ tweet.created_at|date:"M d, o" }}
					</span>
				</div>
				<div class="h-10 flex p-2 gap-3">
					<div class="text-xs h-full flex items-center justify-center w-fit gap-1">
						<b>{{ tweet.retweets.all|length }}</b><span class="text-gray-500">Retweets</span>
					</div>
					<div class="text-xs h-full flex items-center justify-center w-fit gap-1">
						<b>{{ tweet.replies.all|length }}</b><span class="text-gray-500">Replies</span>
					</div>
					<div class="text-xs h-full flex items-center justify-center w-fit gap-1">
						<b>{{ tweet.likes.all|length }}</b><span class="text-gray-500">Likes</span>
					</div>
				</div>
				<div class="h-10 w-full flex justify-evenly">
					{% tweet_liked_by tweet request.user as liked %}
					<button onclick=""><i class="fal fa-comment text-lg"></i> </button>
					<button><i class="fal fa-arrows-retweet"></i> </button>
					<button onclick="like('{% url 'tweet:like' tweet.id %}', this)"><i class="{% if liked %}fas{% else %}fal{% endif %} fa-heart text-lg"></i></button>
					<button><i class="fal fa-share-nodes text-lg"></i></button>
				</div>
				<!-- reply section -->
				<form method="post" enctype="multipart/form-data" action="{% url 'tweet:create' %}">
					<input type="hidden" name="reply_mode" value="{{ tweet.reply_mode }}">
					<input type="hidden" name="reply_to" value="{{ tweet.id }}">
					<div onclick="show_reply(this)" class="reply_section py-2">
						<div class="reply_to  hidden text-xs">Replying to <a class="text-blue-400" href="{% url 'profile:detail' tweet.user.profile.id %}">@{{ tweet.user.username }}</a></div>
						<div class="reply_profile flex flex-col items-center">
							<div class="bg-gray-300 ring-[1px] w-12 h-12 rounded-full overflow-hidden flex items-center justify-center">
								{% if request.user.profile.photo %}
								<img class="w-full h-full object-cover" src="{{ request.user.profile.photo.url }}">
								{% else %}
								<i class="fas fa-user text-white text-2xl"></i>
								{% endif %}
							</div>
						</div>
						<div class="reply_input flex items-center">
							<textarea name="text" class="w-full h-fit outline-none text-lg resize-none" rows="1" placeholder="Tweet your reply"></textarea>
							<div class="flex items-center justify-between">
								<div class="utils hidden text-blue-400">
									<label>
										<input name="image" type="file" class="hidden">
										<i class="fal fa-image"></i>
									</label>
									<label>
										<input name="video" type="file" class="hidden">
										<i class="fal fa-video"></i>
									</label>
								</div>
								<button class="px-4 py-1 rounded-full bg-blue-300 text-white font-bold">Reply</button>
							</div>
						</div>
					</div>
				</form>
				<!-- reply section -->
				{% for reply in tweet.replies.all %}
				<div class="p-3">
					<div class="flex gap-3">
						<div class="flex flex-col items-center w-fit">
							<div class="w-12 h-12 rounded-full ring-[1px] bg-gray-300 flex-shrink-0 flex items-center justify-center overflow-hidden">
								{% if reply.user.profile.photo %}
								<img class="w-full h-full object-cover" src="{{ reply.user.profile.photo.url }}">
								{% else %}
								<i class="fas fa-user text-white text-2xl"></i>
								{% endif %}
							</div>
							{% if reply.replies.all|length > 0 %}
							<div class="h-full w-[2px] bg-gray-300 my-1"></div>
							{% endif %}
						</div>
						<div class="w-full">
							<div class="w-full flex items-center justify-between">
								<div class="flex gap-1 w-full items-center">
									<h4 class="font-bold">{{ reply.user.profile.name }}</h4>
									<span class="text-gray-500">@{{ reply.user.username }}</span>
									<div class="rounded-full border border-gray-500 w-0 h-0"></div>
									<small class="text-gray-500 text-xs flex items-center">{{ reply.created_at|timesince }} ago</small>
								</div>
								<button><i class="fal fa-ellipsis"></i></button>
							</div>
							<a href="{% url 'tweet:detail' reply.id %}">
								<!-- {% if reply.reply_to %} -->
								<!-- <div class="text-xs"> -->
								<!-- 	<span class="text-gray-500">Replying to </span><a href="{% url 'tweet:detail' reply.reply_to.id %}" class="text-blue-400">@{{ reply.reply_to.user }}</a> -->
								<!-- </div> -->
								<!-- {% endif %} -->
								<p class="text-sm">{{ reply.text }}</p>
								<div class="w-full">
									{% for media in reply.media_set.all %}
										{% if media.content_type == "image/jpeg" or media.content_type == "image/png" %}
										<div class="w-full rounded-xl max-h-80 overflow-hidden ring-[1px] ring-gray-300 mt-2">
											<img class="w-full h-full object-cover" src="{{ media.file.url }}">
										</div>
										{% elif media.content_type == "video/mp4" or media.content_type == "video/3gp" %}
										<div class="w-full rounded-xl max-h-80 overflow-hidden ring-[1px] ring-gray-300 mt-2">
											<video controls class="w-full h-full object-cover" src="{{ media.file.url }}"></video>
										</div>
										{% endif %}			
									{% endfor %}
								</div>
							</a>
							<div class="flex h-10 items-center justify-between child:w-full">
								{% tweet_liked_by reply request.user as liked %}
								<button onclick="location.assign('{% url 'tweet:detail' reply.id %}')"><i class="fal fa-comment"></i> <span class="text-xs">{{ reply.replies.all|length }}</span></button>
								<button><i class="fal fa-arrows-retweet"></i> <span class="text-xs">{{ reply.retweets.all|length }}</span></button>
								<button onclick="like('{% url 'tweet:like' reply.id %}', this)"><i class="{% if liked %}fas{% else %}fal{% endif %} fa-heart"></i> <span class="text-xs total">{{ reply.likes.all|length }}</span></button>
								<button><i class="fal fa-share-nodes"></i></button>
							</div>
						</div>
					</div>
					{% if reply.replies.count %}
					<!-- reply reply -->
					<div class="flex gap-3">
						<div class="flex flex-col items-center w-fit">
							<div class="w-10 h-10 mx-1 rounded-full ring-[1px] bg-gray-300 flex-shrink-0 flex items-center justify-center overflow-hidden">
								{% if reply.replies.first.user.profile.photo %}
								<img class="w-full h-full object-cover" src="{{ reply.replies.first.user.profile.photo.url }}">
								{% else %}
								<i class="fas fa-user text-white text-2xl"></i>
								{% endif %}
							</div>
						</div>
						<div class="w-full">
							<div class="w-full flex justify-between">
								<div class="flex gap-1 w-full items-center">
									<h4 class="font-bold">{{ reply.replies.first.user.profile.name }}</h4>
									<span class="text-gray-500">@{{ reply.replies.first.user.username }}</span>
									<div class="rounded-full border border-gray-500 w-0 h-0"></div>
									<small class="text-gray-500 text-xs flex items-center">{{ reply.replies.first.created_at|timesince }} ago</small>
								</div>
								<button><i class="fal fa-ellipsis"></i></button>
							</div>
							<a href="{% url 'tweet:detail' reply.replies.first.id %}">
								<!-- {% if reply.replies.first.reply_to %} -->
								<!-- <div class="text-xs"> -->
								<!-- 	<span class="text-gray-500">Replying to </span><a href="{% url 'tweet:detail' reply.replies.first.reply_to.id %}" class="text-blue-400">@{{ reply.replies.first.reply_to.user }}</a> -->
								<!-- </div> -->
								<!-- {% endif %} -->
								<p class="text-sm">{{ reply.replies.first.text }}</p>
								<div class="w-full mt-2">
									{% for media in reply.replies.first.media_set.all %}
									{% if media.content_type == "image/jpeg" or "image/png" %}
									<div class="w-full rounded-xl max-h-80 overflow-hidden ring-[1px] ring-gray-300">
										<img class="w-full h-full object-cover" src="{{ media.file.url }}">
									</div>
									{% endif %}			
									{% endfor %}
								</div>
							</a>
							<div class="flex h-10 items-center justify-between child:w-full">
								{% tweet_liked_by reply.replies.first request.user as liked %}
								<button onclick="location.assign('{% url 'tweet:detail' reply.replies.first.id %}')"><i class="fal fa-comment"></i> <span class="text-xs">{{ reply.replies.first.replies.all|length }}</span></button>
								<button><i class="fal fa-arrows-retweet"></i> <span class="text-xs">{{ reply.replies.first.retweets.all|length }}</span></button>
								<button onclick="like('{% url 'tweet:like' reply.replies.first.id %}', this)"><i class="{% if liked %}fas{% else %}fal{% endif %} fa-heart"></i> <span class="text-xs total">{{ reply.replies.first.likes.all|length }}</span></button>
								<button><i class="fal fa-share-nodes"></i></button>
							</div>
						</div>
					</div>
					<!-- reply reply -->
					{% endif %}
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
<script>
	function like(url, el){
			let total = el.querySelector('.total')
			let icon = el.querySelector('i')
			fetch(url).then(r=>r.json()).then(res=>{
				if (res.action == 'add'){
						total.innerHTML = parseInt(total.innerHTML)+1
						icon.classList.replace('fal', 'fas')
					}
				else{
						total.innerHTML = parseInt(total.innerHTML)-1
						icon.classList.replace('fas', 'fal')
					}
				})
	}

	function show_reply(e){
			e.querySelector('.reply_to').classList.remove("hidden")
			e.querySelector('.reply_input').classList.remove("flex")
			e.querySelector('.reply_input').querySelector('textarea').style.height = "6rem"
			e.querySelector('.reply_input').querySelector('.utils').classList.remove("hidden")
	}
</script>
{% endblock %}