account_app/urls.py
from django.urls import path
from . import views

app_name = "account"


urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("create/", views.Create.as_view(), name="create"),
    path("logout/", views.logout, name="logout"),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core_app.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/models.py
from django.db import models

# Create your models here.

account_app/forms.py
from django import forms
from core_app import models


class UserForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ["username", "password", "first_name", "last_name"]

account_app/views.py
from django.shortcuts import redirect, render, reverse
from django.views import View
from django.http import request
from . import forms
from core_app import decorators, models, mixins
from django.contrib.auth import authenticate, login, logout as auth_logout
from core_app import utils

# Create your views here.

class Login(mixins.PreventWhenLoggedIn, View):
    template_name = "account_app/login.html"

    def get(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        return render(req, self.template_name, ctx)

    def post(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {
            'input': {}
        }
        username = req.POST.get("username")
        password = req.POST.get("password")
        next_url = req.GET.get("next")
        token = req.POST.get('g-recaptcha-response')
        ctx['input']["username"] = username
        ctx["input"]["password"] = password

        if not utils.verify_recaptcha(token):
            ctx["captcha"] = "failed to validate recaptcha"
            return render(req, self.template_name, ctx)

        if username and password:
            user = authenticate(username=username, password=password)
            if user:
                login(req, user)
                return redirect(next_url or reverse("index"))

        return render(req, self.template_name, ctx)


class Create(View):
    template_name = "account_app/create.html"

    def get(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        form = forms.UserForm()
        ctx["form"] = form
        return render(req, self.template_name, ctx)

    def post(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        form = forms.UserForm(req.POST)
        token = req.POST.get('g-recaptcha-response')

        if not utils.verify_recaptcha(token):
            ctx['error'] = 'cannot verify recaptcha'
            return render(req, self.template_name, ctx)

        if form.is_valid():
            data = form.cleaned_data
            user = models.User.objects.create_user(**data)
            return redirect(reverse("account:login") + f"?{req.GET.urlencode()}")

        ctx["form"] = form

        return render(req, self.template_name, ctx)


def logout(req: request.HttpRequest, *args, **kwargs):
    param = req.GET.urlencode()
    auth_logout(req)
    return redirect(reverse("account:login") + f"?{param}")

templates/account_app/create.html
{% extends 'skeleton/base.html' %}
{% load core %}
{% block utils %}
<a href="{% url 'index' %}"><i class="fab fa-twitter text-blue-500"></i></a>
<a title="login" href="{% url 'account:login' %}"><i class="fal fa-arrow-right-to-bracket"></i></a>
{% endblock %}
{% block body %}
<div class="p-5 h-full">
	<h1 class="text-2xl font-bold">Create your account</h1>
	<form action="{% url 'account:create' %}" class="h-full flex flex-col gap-3 pt-40 child:flex-shrink-0 items-center" method="post">
		<label class="relative h-12 w-full max-w-sm block">
			<input class="outline-none ring-[1.5px] ring-gray-300 focus:ring-[2px] focus:ring-blue-500 rounded-sm transition-all h-full w-full px-3 peer" placeholder=" " name="username" value="{{ input.username }}">
			<span class="absolute peer-placeholder-shown:top-1/2 top-0 -translate-y-1/2 left-3 bg-white px-1 peer-placeholder-shown:text-lg text-xs text-gray-500 peer-focus:text-blue-500 transition-all">Name</span>
		</label>
		<label class="relative h-12 w-full max-w-sm block">
			<input class="outline-none ring-[1.5px] ring-gray-300 focus:ring-[2px] focus:ring-blue-500 rounded-sm transition-all h-full w-full px-3 peer" placeholder=" " name="password" value="{{ input.password }}">
			<span class="absolute peer-placeholder-shown:top-1/2 top-0 -translate-y-1/2 left-3 bg-white px-1 peer-placeholder-shown:text-lg text-xs text-gray-500 peer-focus:text-blue-500 transition-all">Password</span>
		</label>
		<div class="g-recaptcha mb-40" data-sitekey="{% recaptcha_site_key %}"></div>
		<div class="absolute -translate-y-full bottom-0 left-0 z-[999] bg-white border-t w-full p-5">
			<div class="flex items-center justify-between">
				<button type="reset" class="rounded-full bg-white border w-fit px-4 py-1">Clear</button>
				<button class="rounded-full bg-black text-white w-fit px-4 py-1">Next</button>
			</div>
		</div>
	</form>
</div>
<script src="https://www.google.com/recaptcha/api.js" async defer> </script>
{% endblock %}

templates/account_app/login.html
{% extends 'skeleton/base.html' %}
{% load core %}
{% block utils %}
<a href="{% url 'account:create' %}?{{ request.GET.urlencode }}" class="text-xs hover:text-blue-500" title="register account"><i class="fal fa-address-card"></i></a>
{% endblock %}
{% block body %}
<div class="p-5 h-full">
	<h1 class="text-2xl font-bold">To get started, first enter your username and password</h1>
	<form action="{% url 'account:login' %}" class="h-full flex flex-col gap-3 pt-40 child:flex-shrink-0 items-center" method="post">
		<label class="relative h-12 w-full max-w-sm block">
			<input class="outline-none ring-[1.5px] ring-gray-300 focus:ring-[2px] focus:ring-blue-500 rounded-sm transition-all h-full w-full px-3 peer z-10" placeholder=" " name="username" value="{{ input.username }}">
			<span class="absolute peer-placeholder-shown:top-1/2 top-0 -translate-y-1/2 left-3 bg-white peer-placeholder-shown:text-lg text-xs text-gray-500 peer-focus:text-blue-500 transition-all peer-placeholder-shown:bg-transparent">Username</span>
		</label>
		<label class="relative h-12 w-full max-w-sm block">
			<input class="outline-none ring-[1.5px] ring-gray-300 focus:ring-[2px] focus:ring-blue-500 rounded-sm transition-all h-full w-full px-3 peer z-10" placeholder=" " name="password" value="{{ input.password }}">
			<span class="absolute peer-placeholder-shown:top-1/2 top-0 -translate-y-1/2 left-3 bg-white peer-placeholder-shown:text-lg text-xs text-gray-500 peer-focus:text-blue-500 transition-all peer-placeholder-shown:bg-transparent">Password</span>
		</label>
		<div class="g-recaptcha mb-40" data-sitekey="{% recaptcha_site_key %}"></div>
		<div class="absolute bottom-0 left-0 z-[999] bg-white border-t w-full p-5">
			<div class="flex items-center justify-between">
				<button type="reset" class="rounded-full bg-white border w-fit px-4 py-1">Clear</button>
				<button class="rounded-full bg-black text-white w-fit px-4 py-1">Next</button>
			</div>
		</div>
	</form>
</div>
<script src="https://www.google.com/recaptcha/api.js" async defer> </script>
{% endblock %}

templates/account_app/logout.html
{% extends 'skeleton.html' %}
{% block body %}
{% endblock %}