profile_app/urls.py
from django.urls import path
from . import views

app_name = "profile"
urlpatterns = [
    path("create/", views.Create.as_view(), name="create"),
    path("search/", views.profile_all, name='search'),
    path("update/", views.Update.as_view(), name='update'),
    path("unfollow/", views.unfollow, name='unfollow'),
    path("follow/", views.follow, name='follow'),
    path("<id>/", views.Detail.as_view(), name="detail"),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core_app.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_app/models.py
from django.db import models

# Create your models here.

profile_app/forms.py
from django import forms
from core_app import models

class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['name', 'photo', 'cover_photo', 'bio', 'date_of_birth']

class UpdateProfileForm(forms.Form):
    name = forms.CharField(max_length=20, required=False)
    photo = forms.ImageField(required=False)
    cover_photo = forms.ImageField(required=False)
    bio = forms.CharField(widget=forms.Textarea, required=False)
    date_of_birth = forms.DateField(required=False)

profile_app/views.py
from django.shortcuts import redirect, render, get_object_or_404, reverse
from django.views import View
from django.http import request, response
from core_app import mixins, models, decorators
from django.core import serializers
from . import forms
import re

# Create your views here.


class Detail(View):
    template_name = "profile_app/detail.html"

    def get(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        profile = get_object_or_404(models.Profile, id=kwargs.get("id"))
        ctx["profile"] = profile
        ctx["following"] = profile.followers.filter(id=req.user.id).first() != None
        return render(req, self.template_name, ctx)

class Update(mixins.ProfileRequired, View):
    template_name = "profile_app/update.html"
    def get(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        ctx['profile'] = req.user.profile
        return render(req, self.template_name, ctx)

    def post(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        ctx['form'] = forms.UpdateProfileForm(req.POST, req.FILES)
        ctx['profile'] = req.user.profile
        if ctx['form'].is_valid():
            data = {}
            data2 = ctx['form'].cleaned_data
            for k in data2:
                if data2[k]:
                    data[k] = data2[k]
            for k in data:
                ctx['profile'].__dict__[k] = data[k]
            ctx['profile'].save()
            return redirect(reverse('profile:detail', kwargs={'id': ctx['profile'].id}))

        return render(req, self.template_name, ctx)

class Create(View):
    template_name = "profile_app/create.html"

    def get(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        ctx['form'] = forms.ProfileForm()
        return render(req, self.template_name, ctx)

    def post(self, req: request.HttpRequest, *args, **kwargs):
        ctx = {}
        ctx['form'] = forms.ProfileForm(req.POST, req.FILES)
        if ctx['form'].is_valid():
            print("valid")
            data = ctx['form'].cleaned_data
            profile = models.Profile.objects.create(
                user=req.user,
                **data
            )
            profile.save()
            if req.GET.get('next'):
                return redirect(req.GET.get('next'))
            return redirect('/')
        else:
            return render(req, self.template_name, ctx)

def profile_all(req: request.HttpRequest, *args, **kwargs):
    users = models.User.objects.filter(
        username__contains=req.GET.get('name')
    )
    profiles = [user.profile for user in users]
    data = {
            'profiles':[
        {
            'id': profile.user.id,
            'photo': False if profile.photo.name == '' else profile.photo.url,
            'name': profile.name,
            'user': {
                'username': profile.user.username
            }
        } for profile in profiles
    ]
    }
    return response.JsonResponse(data)

def unfollow(req: request.HttpRequest, *args, **kwargs):
    if req.method != "POST":
        return response.HttpResponseNotAllowed(['POST'])
    user = get_object_or_404(models.User, id=req.POST.get('user'))
    if user == req.user: return response.HttpResponse("cant unfollow self")
    req.user.profile.unfollow(user)
    return redirect(reverse('profile:detail', kwargs={'id': user.profile.id}))

def follow(req: request.HttpRequest, *args, **kwargs):
    if req.method != "POST":
        return response.HttpResponseNotAllowed(['POST'])
    user = get_object_or_404(models.User, id=req.POST.get('user'))
    if user == req.user: return response.HttpResponse("cant follow self")
    req.user.profile.follow(user)
    return redirect(reverse('profile:detail', kwargs={'id': user.profile.id}))

templates/profile_app/create.html
{% extends 'skeleton/tulang.html' %}
{% block body %}
<div class="bg-gray-100">
	<div class="max-w-xl m-auto bg-white h-screen">
		<div class="w-full flex justify-between h-10 items-center p-6 sticky top-0 left-0 backdrop-blur-lg z-[999]">
			<div class="flex h-full items-center gap-3">
				<button onclick="history.back()"><i class="far fa-arrow-left text-lg"></i></button>
				<span class="font-bold">Create Profile</span>
			</div>
			<button onclick="document.querySelector('form#profile').submit()" class="px-4 py-1 bg-black text-white rounded-full">Create</button>
		</div>
		<div class="p-3 pt-0">
			<form id="profile" method="post" action="{% url 'profile:create' %}" enctype="multipart/form-data">
				<div class="w-full bg-gray-400 h-40 flex items-center justify-center relative">
					{% if profile.cover_photo %}
					<img class="w-full h-full absolute top-0 left-0 z-0 object-cover" src="{{ profile.cover_photo.url }}">
					{% endif %}
					<label class="w-10 h-10 rounded-full bg-black/20 flex items-center justify-center z-10">
						<input name="cover_photo" type="file" class="hidden">
						<i class="fal fa-camera text-white text-xl"></i>
					</label>
				</div>
				<div class="relative h-10 mb-5">
					<div class="w-20 h-20 ring-white ring bg-gray-300 rounded-full absolute bottom-0 left-5 flex items-center justify-center overflow-hidden">
						{% if profile.photo %}
						<img id="photo-img" class="w-full h-full absolute top-0 left-0 z-0 object-cover" src="{{ profile.photo.url }}">
						{% else %}
						<img id="photo-img" class="w-full h-full absolute top-0 left-0 z-0 object-cover hidden">
						{% endif %}
						<label class="w-10 h-10 rounded-full bg-black/20 flex items-center justify-center z-10">
							<input name="photo" type="file" class="hidden" onchange="document.querySelector('#photo-img').src=URL.createObjectURL(this.files[0]);document.querySelector('#photo-img').classList.remove('hidden')">
							<i class="fal fa-camera text-white text-xl"></i>
						</label>
					</div>
				</div>
				<label class="ring-[1px] ring-gray-300 hover:ring-[1.5px] hover:ring-blue-400  py-4 px-2 rounded-md relative w-full block mb-5">
					<input name="name" type="text" maxlength="20" class="outline-none peer mt-2 placeholder-shown:mt-0" placeholder=" " required value="{{ profile.name }}">
					<span class="absolute left-2 top-2 peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 transition-all peer-placeholder-shown:text-lg text-sm text-blue-500 peer-placeholder-shown:text-gray-500">Name</span>
				</label>
				<label class="ring-[1px] ring-gray-300 hover:ring-[1.5px] hover:ring-blue-400  py-4 px-2 rounded-md relative w-full block mb-5">
					<textarea name="bio" class="outline-none w-full h-full peer py-2" placeholder=" ">{{ profile.bio }}</textarea>
					<span class="absolute left-2 top-2 peer-focus:top-2 peer-focus:translate-y-0 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 transition-all peer-placeholder-shown:text-lg text-sm text-blue-500 peer-placeholder-shown:text-gray-500 peer-focus:text-sm peer-focus:text-blue-500">Bio</span>
				</label>
				<div class="flex items-center text-sm gap-1">
					<span>Date Birth</span>
					<div class="h-0 w-0 border border-gray-300 rounded-full"></div>
					<label class="text-blue-400" for="hh">Change</label>
				</div>
				<input name="date_of_birth" class="border-none bg-transparent outline-none w-fit text-2xl font-bold" type="date" id="hh" value="{{ profile.date_of_birth|date:"Y-m-d" }}">
			</form>
		</div>
	</div>
</div>
<script>
	function change_profile_photo(f){
			let photo = document.getElementById('photo')
			let url = URL.createObjectURL(f)
			photo.innerHTML = `<img class="w-full h-full object-cover" src=${url}>`
		}

	function change_size(el){
			alert(el)
		}
</script>
{% endblock %}

templates/profile_app/detail.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{{ TITLE }}</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<link rel="stylesheet" href="{% static 'css/style.css' %}?{% now "%U" %}">
		<link rel="stylesheet" href="{% static 'css/icon.css' %}">
		<script src="{% static 'js/account/detail.js' %}?{% now "%U" %}" defer></script>
		<meta name="theme-color" content="#000">
	</head>
	<body class="bg-gray-100">
		<div class="h-[200vh] max-w-xl m-auto bg-white">

			<!-- nav -->
			<div id="nav" class="flex fixed top-0 left-1/2 -translate-x-1/2 items-center justify-between h-14 w-full px-3 z-50 duration-500 transition-all max-w-xl">
				<button id="back" class="bg-black/50 w-8 h-8 rounded-full"><i class="fas fa-arrow-left text-white"></i></button>
				<div>
					<button class="bg-black/50 w-8 h-8 rounded-full"><i class="fal fa-magnifying-glass text-white"></i></button>
					<button class="bg-black/50 w-8 h-8 rounded-full"><i class="far fa-ellipsis-vertical text-white"></i></button>
				</div>
			</div>
			<!-- nav -->

			<!-- cover -->
			<div id="cover" class="bg-blue-400 w-full h-40">
				{% if profile.cover_photo %}
				<img class="w-full h-full object-cover" src="{{ profile.cover_photo.url }}">
				{% endif %}
			</div>
			<!-- cover -->
			
			<!-- content -->
			<div class="px-3 w-full">
				<div class="h-14 w-full flex items-center justify-end relative">
					<div id="profile" class="h-24 w-24 bg-gray-300 rounded-full ring-4 ring-white absolute bottom-3 left-0 overflow-hidden flex items-center justify-center">
						{% if profile.photo %}
						<img class="w-full h-full object-cover" src="{{ profile.photo.url }}">
						{% else %}
						<i class="fas fa-user text-white text-5xl"></i>
						{% endif %}
					</div>
					{% if request.user == profile.user %}
					<button onclick="location.assign('{% url 'profile:update' %}')" class="border-[1px] px-4 py-1 rounded-full font-bold hover:bg-gray-100">Set up profile</button>
					{% elif following %}
					<form action="{% url 'profile:unfollow' %}" method="post">
						<input type="hidden" name="user" value="{{ profile.user.id }}">
						<button class="border-[1px] px-4 py-1 rounded-full font-bold hover:bg-gray-100">Unfollow</button>
					</form>
					{% else %}
					<form action="{% url 'profile:follow' %}" method="post">
						<input type="hidden" name="user" value="{{ profile.user.id }}">
						<button class="border-[1px] px-4 py-1 rounded-full bg-black text-white font-bold hover:bg-black/80">Follow</button>
					</form>
					{% endif %}
				</div>
				<div class="mt-1 mb-3">
					<h2 class="font-bold text-2xl">{{ profile.name }}</h2>
					<h4 class="font-bold text-gray-500">@{{ profile.user.username }}</h4>
				</div>
				<div class="text-gray-500">
					<small><i class="far fa-calendar"></i> Joined {{ profile.user.date_joined|date:"M Y" }}</small>
				</div>
				<div class="flex items-center text-gray-500 gap-3 my-2 text-xs">
					<h6>
						<span class="font-bold text-black">{{ profile.following|length }}</span> Following
					</h6>
					<h6>
						<span class="font-bold text-black">{{ profile.followers|length }}</span> Followers
					</h6>
				</div>

				<!-- tab -->
				<div class="overflow-hidden">
					<nav class="w-full flex items-center justify-evenly child:h-10 child:flex child:items-center child:justify-center [&] border-b child:text-sm">
						<label>
							<input class="hidden peer" type="radio" name="tab" checked>
							<div class="h-full ring-b flex items-center justify-center before:peer-checked:h-1 text-gray-500 peer-checked:text-black font-bold">
								Tweets
							</div>
						</label>
						<label>
							<input class="hidden peer" type="radio" name="tab">
							<div class="h-full ring-b flex items-center justify-center before:peer-checked:h-1 peer-checked:text-black text-gray-500 font-bold">
								Tweets & replies
							</div>
						</label>
						<label>
							<input class="hidden peer" type="radio" name="tab">
							<div class="h-full ring-b flex items-center justify-center before:peer-checked:h-1 peer-checked:text-black text-gray-500 font-bold">
								Media
							</div>
						</label>
						<label>
							<input class="hidden peer" type="radio" name="tab">
							<div class="h-full ring-b flex items-center justify-center before:peer-checked:h-1 peer-checked:text-black text-gray-500 font-bold">
								Likes
							</div>
						</label>
					</nav>
					<ul id="tabs" class="w-full child:w-full flex child:flex-shrink-0 transition-all">
						<li>Elit inventore recusandae sapiente doloribus aut Sequi soluta voluptatibus neque a harum Amet quae facere ullam consequatur repellat? Blanditiis obcaecati provident reiciendis porro soluta Veniam ea nemo obcaecati sint eos?</li>
						<li>Consectetur eum corporis excepturi in commodi iste Ab cupiditate repudiandae</li>
						<li>Elit quidem molestiae dolor animi</li>
						<li></li>
					</ul>
				</div>
				<!-- tab -->

			</div>
			<!-- content -->
		</div>
	</body>
</html>

templates/profile_app/update.html
{% extends 'skeleton/tulang.html' %}
{% block body %}
<div class="bg-gray-100">
	<div class="max-w-xl m-auto bg-white h-screen">
		<div class="w-full flex justify-between h-10 items-center p-6 sticky top-0 left-0 backdrop-blur-lg z-[999]">
			<div class="flex h-full items-center gap-3">
				<button onclick="history.back()"><i class="far fa-arrow-left text-lg"></i></button>
				<span class="font-bold">Update Profile</span>
			</div>
			<button onclick="document.querySelector('form#profile').submit()" class="px-4 py-1 bg-black text-white rounded-full">Save</button>
		</div>
		<div class="p-3 pt-0">
			<form id="profile" method="post" action="{% url 'profile:update' %}" enctype="multipart/form-data">
				<div class="w-full bg-gray-400 h-40 flex items-center justify-center relative">
					{% if profile.cover_photo %}
					<img class="w-full h-full absolute top-0 left-0 z-0 object-cover" src="{{ profile.cover_photo.url }}">
					{% endif %}
					<label class="w-10 h-10 rounded-full bg-black/20 flex items-center justify-center z-10">
						<input name="cover_photo" type="file" class="hidden">
						<i class="fal fa-camera text-white text-xl"></i>
					</label>
				</div>
				<div class="relative h-10 mb-5">
					<div class="w-20 h-20 ring-white ring bg-gray-300 rounded-full absolute bottom-0 left-5 flex items-center justify-center overflow-hidden">
						{% if profile.photo %}
						<img id="photo-img" class="w-full h-full absolute top-0 left-0 z-0 object-cover" src="{{ profile.photo.url }}">
						{% else %}
						<img id="photo-img" class="w-full h-full absolute top-0 left-0 z-0 object-cover hidden">
						{% endif %}
						<label class="w-10 h-10 rounded-full bg-black/20 flex items-center justify-center z-10">
							<input name="photo" type="file" class="hidden" onchange="document.querySelector('#photo-img').src=URL.createObjectURL(this.files[0]);document.querySelector('#photo-img').classList.remove('hidden')">
							<i class="fal fa-camera text-white text-xl"></i>
						</label>
					</div>
				</div>
				<label class="ring-[1px] ring-gray-300 hover:ring-[1.5px] hover:ring-blue-400  py-4 px-2 rounded-md relative w-full block mb-5">
					<input name="name" type="text" maxlength="20" class="outline-none peer mt-2 placeholder-shown:mt-0" placeholder=" " required value="{{ profile.name }}">
					<span class="absolute left-2 top-2 peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 transition-all peer-placeholder-shown:text-lg text-sm text-blue-500 peer-placeholder-shown:text-gray-500">Name</span>
				</label>
				<label class="ring-[1px] ring-gray-300 hover:ring-[1.5px] hover:ring-blue-400  py-4 px-2 rounded-md relative w-full block mb-5">
					<textarea name="bio" class="outline-none w-full h-full peer py-2" placeholder=" ">{{ profile.bio }}</textarea>
					<span class="absolute left-2 top-2 peer-focus:top-2 peer-focus:translate-y-0 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 transition-all peer-placeholder-shown:text-lg text-sm text-blue-500 peer-placeholder-shown:text-gray-500 peer-focus:text-sm peer-focus:text-blue-500">Bio</span>
				</label>
				<div class="flex items-center text-sm gap-1">
					<span>Date Birth</span>
					<div class="h-0 w-0 border border-gray-300 rounded-full"></div>
					<label class="text-blue-400" for="hh">Change</label>
				</div>
				<input name="date_of_birth" class="border-none bg-transparent outline-none w-fit text-2xl font-bold" type="date" id="hh" value="{{ profile.date_of_birth|date:"Y-m-d" }}">
			</form>
		</div>
	</div>
</div>
<script>
	function change_profile_photo(f){
			let photo = document.getElementById('photo')
			let url = URL.createObjectURL(f)
			photo.innerHTML = `<img class="w-full h-full object-cover" src=${url}>`
		}

	function change_size(el){
			alert(el)
		}
</script>
{% endblock %}