account_app/urls.py
from django.urls import path
from . import views

app_name = "account"


urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("create/", views.Create.as_view(), name="create"),
    path("logout/", views.logout, name="logout"),
]

profile_app/urls.py
from django.urls import path
from . import views

app_name = "profile"
urlpatterns = [
    path("create/", views.Create.as_view(), name="create"),
    path("search/", views.profile_all, name='search'),
    path("update/", views.Update.as_view(), name='update'),
    path("unfollow/", views.unfollow, name='unfollow'),
    path("follow/", views.follow, name='follow'),
    path("<id>/", views.Detail.as_view(), name="detail"),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core_app.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet_app/urls.py
from django.urls import path
from . import views


app_name = "tweet"
urlpatterns = [
    path("create/", views.Create.as_view(), name='create'),
    path('likes/<pk>/', views.like, name='like'),
    path('<pk>/', views.Detail.as_view(), name='detail'),
]

templates/skeleton/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{{ TITLE }}</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="theme-color" content="rgb(59, 130, 246)">
		<link rel="stylesheet" href="{% static 'css/style.css' %}?{% now "%U" %}">
		<link rel="stylesheet" href="{% static 'css/icon.css' %}">
	</head>
	<body class="bg-gray-100 ">
		<div class="relative max-w-xl m-auto h-screen overflow-hidden">
			<!-- profile div -->
			{% if request.user.is_authenticated %}
			<input type="checkbox" class="hidden peer" id="profile">
			<div class="absolute top-0 left-0 w-full h-screen duration-500 z-[999] -translate-x-full transition-all peer-checked:translate-x-0 ease-in-out opacity-0 peer-checked:opacity-100 overflow-hidden">
							<input type="checkbox" class="hidden peer" id="account-utils">
							<div class="w-10/12 relative bg-white h-full p-5 peer-checked:blur-sm peer-checked:bg-gray-50 transition-all duration-300">
								<div class="flex items-center justify-between">
									<span class="text-xl font-bold">Account info</span>
								<label class="hover:cursor-pointer" for="profile"><i class="fas fa-x text-xl hover:scale-110 transition-all"></i></label>
								</div>
								<div class="w-full border-b py-3">
									<div class="w-14 h-14 bg-gray-300 rounded-full overflow-hidden shadow-sm ring-[1px] flex items-center justify-center">
										{% if request.user.profile.photo %}
										<img class="w-full h-full object-cover" src="{{ request.user.profile.photo.url }}">
										{% else %}
										<i class="fas fa-user text-4xl text-white"></i>
										{% endif %}
									</div>
									<div class="my-2 flex items-center justify-between">
										<div>
											<h3 class="font-bold text-xl">{{ request.user.profile.name }}</h3>
											<h5 class="text-gray-500">@{{ request.user.username }}</h5>
										</div>
										<label class="hover:cursor-pointer" for="account-utils"><i class="fas fa-angle-down"></i></label>
									</div>
									<div class="flex items-center gap-3">
										<h6><span class="font-bold">{{ request.user.profile.following|length }}</span> <small class="text-gray-500">Following</small></h6>
										<h6><span class="font-bold">{{ request.user.profile.followers|length }}</span> <small class="text-gray-500">Followers</small></h6>
									</div>
								</div>
								<ol>
									<li><a href="{% url 'profile:detail' request.user.profile.id %}" class="w-full h-full block transition-all"><i class="fal fa-user text-xl my-3 mr-3"></i> Profile</a></li>
								</ol>
							</div>
							<div class="absolute bottom-0 translate-y-full left-0 w-full p-5 bg-white rounded-[30px_30px_0_0] shadow-lg peer-checked:translate-y-0 transition-all duration-300">
								<label class="absolute top-1 left-1/2 -translate-x-1/2 hover:cursor-pointer" for="account-utils"><div class="w-10 h-2 rounded-full bg-gray-300"></div></label>
								<h4 class="font-bold text-xl">Accounts</h4>
								<div class="my-3 flex items-center justify-between">
									<div class="flex items-center gap-3">
										<div class="w-10 h-10 rounded-full bg-gray-300 overflow-hidden shadow-sm ring-[1px] flex items-center justify-center">
											{% if request.user.profile.photo %}
											<img class="w-full h-full object-cover" src="{{ request.user.profile.photo.url }}">
											{% else %}
											<i class="fas fa-user text-2xl text-white"></i>
											{% endif %}
										</div>
										<div>
											<h3 class="font-bold text-xl">{{ request.user.profile.name }}</h3>
											<h5 class="text-gray-500">{{ request.user.username }}</h5>
										</div>
									</div>
									<i class="fas fa-circle-check text-green-400"></i>
								</div>
								<a class="ring-[2px] ring-gray-200 rounded-full h-12 w-full flex items-center justify-center font-bold text-xl pop" href="{% url 'account:logout' %}">logout</a>
							</div>
						</div>
			{% endif %}
			<!-- profile div -->
			
			<div class="bg-white peer-checked:blur-sm peer-checked:bg-black/10 relative transition-all duration-500 w-full h-full">
				<div class="border-b h-14 flex items-center justify-between px-3 py-2">
					<label for="profile" class="hover:cursor-pointer">
						<i class="fal fa-circle-user text-xl"></i>
					</label>
					{% block utils %}
					{% endblock %}
				</div>
				<div id="content" class="overflow-scroll h-screen">
						{% block body %}
						{% endblock %}
				</div>
				{% block nav %}
				{% endblock %}
			</div>
		</div>
		<script>
			let nav_items = document.querySelectorAll('nav > ul > li')
			nav_items.forEach(e=>{
							let a = e.querySelector('a')
							if(a.href == location.origin+location.pathname){
											a.querySelector('i').classList.replace('fal', 'fas')
										}
						})
		</script>
	</body>
</html>

templates/skeleton/nav.html
<nav class="sticky bottom-0 left-0 bg-white h-14 w-screen max-w-xl border-t">
	<ul class="h-full w-full flex items-center">
		<li class="w-full h-full click">
			<a class="flex items-center justify-center h-full w-full" href="{% url 'index' %}"><i class="fal fa-home"></i></a>
		</li>
		<li class="w-full h-full click">
			<a class="flex items-center justify-center h-full w-full" href="{% url 'search' %}"><i class="fal fa-magnifying-glass"></i></a>
		</li>
		<!-- <li class="w-full h-full click"> -->
		<!-- 	<a class="flex items-center justify-center h-full w-full" href="{% url 'index' %}"><i class="fal fa-microphone-lines"></i></a> -->
		<!-- </li> -->
		<li class="w-full h-full click">
			<a class="flex items-center justify-center h-full w-full" href="{% url 'notif' %}"><i class="fal fa-bell"></i></a>
		</li>
		<li class="w-full h-full click">
			<a class="flex items-center justify-center h-full w-full" href="{% url 'index' %}"><i class="fal fa-envelope"></i></a>
		</li>
	</ul>
</nav>

templates/skeleton/tulang.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{{ PAGE_TITLE }}</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		{% block head %}
		{% endblock %}
		<link rel="stylesheet" href="{% static 'css/style.css' %}?{% now "%U" %}">
		<link rel="stylesheet" href="{% static 'css/icon.css' %}">
	</head>
	<body>
		{% block body %}
		{% endblock %}
	</body>
</html>

templates/skeleton/tweet-nav.html
<input type="checkbox" class="hidden peer" id="tweet-nav">
<ul id="tweet-btns" class="absolute bottom-full left-0 rounded-full  peer-checked:z-50 peer-checked:[&>div.hidden]:child:block child:w-14 child:h-14 child:flex child:items-center child:justify-center peer-checked:[&>.small]:child:scale-75 peer-checked:[&>*:not(.small)]:child:scale-100 text-white peer-checked:[&>button.-rotate-90]:child:rotate-0 h-0 overflow-hidden peer-checked:h-fit transition-all peer-checked:overflow-visible">
	<li class="relative">
		<div class="absolute top-1/2 -left-3 -translate-y-1/2 -translate-x-full items-center justify-center text-black hidden">Video</div>
		<button class="w-full h-full scale-0 bg-white rounded-full flex transition-all small items-center justify-center -rotate-90 shadow-md">
			<i class="fal fa-file-video text-blue-500 text-2xl"></i>
		</button>
	</li>
	<li class="relative">
		<div class="absolute top-1/2 -left-3 -translate-y-1/2 -translate-x-full items-center justify-center text-black hidden">Photo</div>
		<button class="w-full h-full scale-0 bg-white rounded-full flex transition-all small items-center justify-center -rotate-90 shadow-md">
			<i class="fal fa-file-image text-blue-500 text-2xl"></i>
		</button>
	</li>
	<li class="relative">
		<div class="absolute top-1/2 -left-3 -translate-y-1/2 -translate-x-full items-center justify-center text-black hidden">Tweet</div>
		<button data-url="{% url 'tweet:create' %}" id="tweet-btn" class="w-full h-full scale-0 bg-blue-500 rounded-full flex transition-all items-center justify-center -rotate-90 shadow-md small">
			<i class="fal fa-feather"></i>
		</button>
	</li>
</ul>
<label for="tweet-nav" class="w-14 h-14 rounded-full bg-blue-500 shadow-md flex items-center justify-center rotate-0 peer-checked:rotate-90 transition-all">
	<i class="fal fa-plus text-white text-2xl"></i>
</label>
<script>
	let tweetNav = document.querySelector("#tweet-nav")
	tweetNav.onchange = ()=>{
			if (tweetNav.checked){
					document.querySelector("#content").style.filter = "blur(4px)"
				}else{
						document.querySelector("#content").style.filter = "blur(0px)"
					}
		}
	let btns = document.querySelectorAll("#tweet-btns button")
	btns.forEach(e=>{
			e.onclick = ()=>{
					location.assign(e.dataset.url)
				}
		})
</script>